seed: 0
exp_name: resnet18_23_MMTM_4


device:
  cuda_device: cuda
  gpu_num_workers: 32

data:
  cv: 10
  img_dir_T2: ./data/raw/T2_images
  img_dir_T1: ./data/raw/T1_images

  fold_dir_T2: ./data/processed/T2
  fold_dir_T1: ./data/processed/T1/folds

  clip_T1:
    min: 0
    max: 2500

  clip_T2:
    min: 0
    max: 1250

  norm: minmax_scaler_-11

  img_dim_T1:
    x: 160
    y: 192
    z: 160

  img_dim_T2:
    x: 331
    y: 396
    z: 101

  model_dir: ./models/cnn
  report_dir: ./reports

  classes:
    - 1
    - 4

  batch_size: 8  #da cambiare con 16

model:
  model_name: FusionNetwork
  model_name_1 : resnet18
  model_name_2 : resnet18
  switch: [ False, False, False, True]
  freeze: False
  pretrained:   #da cambiare
  pretrained_path:
  pretrained_1: True  #da cambiare con true
  pretrained_path_1: ./models/cnn/resnet18_23_no_MMTM
  pretrained_2: True
  pretrained_path_2: ./models/cnn/resnet18_23_no_MMTM

trainer:
  optimizer:
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    mode: min
    patience: 10
  early_stopping: 50
  max_epochs: 300
