seed: 0
exp_name: sfcn2_14_T2_images

device:
  cuda_device: cuda
  gpu_num_workers: 32

data:
  cv: 10
  img_dir: ./data/raw/T2_images                     #path for T2 images
  fold_dir: ./data/processed/folds_T2
  clip:
    min: 0
    max: 1250
  norm: max_scaler_01
  img_dim:
    x: 512
    y: 512
    z: 47
  model_dir: ./models/cnn
  report_dir: ./reports
  classes:
    - 1
    - 4
  batch_size: 16

model:
  model_name: SFCN2
  freeze: False
  pretrained: False                           #cosi funziona il train
  pretrained_path:  ./models/cnn/pretrained/brain_age.p

trainer:
  optimizer:
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    mode: min
    patience: 10
  early_stopping: 50
  max_epochs: 300
