seed: 0
exp_name: sfcn_14

device:
  cuda_device: cuda
  gpu_num_workers: 32

data:
  cv: 10
  img_dir: ./data/raw/T2_images
  fold_dir: ./data/processed/folds
  clip:
    min: 0
    max: 1250
  norm: max_scaler_01
  img_dim:
    x: 331
    y: 396
    z: 101
  model_dir: ./models/cnn
  report_dir: ./reports
  classes:
    - 1
    - 4
  batch_size: 1   #da cambiare

model:
  model_name: SFCN
  freeze: False
  pretrained: False     #da cambiare
  pretrained_path:  ./models/cnn/pretrained/brain_age.p
  avg_shape_T2: [6,7,3]

trainer:
  optimizer:
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    mode: min
    patience: 10
  early_stopping: 50
  max_epochs: 300
