seed: 0
exp_name: FusionNetwork


device:
  cuda_device: cuda
  gpu_num_workers: 32

data:
  cv: 10
  img_dir_T2: ./data/raw/T2_images
  img_dir_T1: ./data/raw/T1_images


  fold_dir_T2: ./data/processed/T2
  fold_dir_T1: ./data/processed/T1/folds

  clip_T1:
    min: 0
    max: 2500

  clip_T2:
    min: 0
    max: 1250

  norm: minmax_scaler_-11

  img_dim_T1:
    x: 160
    y: 192
    z: 160

  img_dim_T2:
    x: 331
    y: 396
    z: 101

  model_dir: ./models/cnn
  report_dir: ./reports

  classes:
    - 1
    - 4

  batch_size: 1  #da cambiare con 16

model:
  model_name: FusionNetwork
  nn1 : resnet18
  nn2 : resnet18
  freeze: False
  pretrained: False  #da cambiare con true
  pretrained_path:  ./models/cnn/pretrained/resnet_18_23dataset.pth

trainer:
  optimizer:
    lr: 0.001
    weight_decay: 0.00001
  scheduler:
    mode: min
    patience: 10
  early_stopping: 50
  max_epochs: 300
